#!/usr/bin/env bash
# set up load balancer
sudo apt-get -y install software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-1.8
sudo apt-get -y update
sudo apt-get -y install haproxy

sudo sed -i -e '$aENABLED=1\n' /etc/default/haproxy 
sudo sed -i -e '$a\listen http-in\n\tbind :80\n\tbalance roundrobin\n\tserver 5469-web-01 3.237.45.16:80 check\n\tserver 5469-web-02 34.232.62.143:80 check\n' /etc/haproxy/haproxy.cfg
sudo service haproxy restart
