#!/usr/bin/env bash
#Install and configure HAProxy

sudo apt update
sudo apt install haproxy -y
haproxy=/etc/default/haproxy
echo "ENABLED=1" | sudo tee -a $haproxy

path=/etc/haproxy/haproxy.cfg
config=\
"
frontend manage_entry
	  bind *:80
	  default_backend my_web_servers
backend my_web_servers
	balance static-rr
	server 5469-web-01 3.237.45.16:80 check
	server 5469-web-02 34.232.62.143:80 check
"

echo "$config" | sudo tee -a "$path"
sudo systemctl restart haproxy.service
